# -*- coding: utf-8; -*-

QUESTIONS = [
    {
        'id': 0,
        'is_name_things': True,
        'total_answers': 30,
        'prompt': "Name 20 of the Largest 30 Cities in the World",
        'passing_score': 20,
        'answers': {
            "tokyo": 0,
            "jakarta": 1,
            "karachi": 2,
            "manila": 3,
            "delhi": 4,
            "seoul": 5,
            "shanghai": 6,
            "beijing": 7,
            "new york city": 8,
            "new york": 8,
            "guangzhou": 9,
            "sao paulo": 10,
            "mexico city": 11,
            "mumbai": 12,
            "osaka": 13,
            "lagos": 14,
            "moscow": 15,
            "dhaka": 16,
            "lahore": 17,
            "los angeles": 18,
            "bangkok": 19,
            "kolkata": 20,
            "buenos aires": 21,
            "tehran": 22,
            "istanbul": 23,
            "shenzhen": 24,
            "rio de janeiro": 25,
            "kinshasa": 26,
            "tianjin": 27,
            "paris": 28,
            "lima": 29
        },
        'names': [
            'Tokyo',
            'Jakarta',
            'Karachi',
            'Manila',
            'Delhi',
            'Seoul',
            'Shanghai',
            'Beijing',
            'New York City',
            'Guangzhou',
            'Sao Paulo',
            'Mexico City',
            'Mumbai',
            'Osaka',
            'Lagos',
            'Moscow',
            'Dhaka',
            'Lahore',
            'Los Angeles',
            'Bangkok',
            'Kolkata',
            'Buenos Aires',
            'Tehran',
            'Istanbul',
            'Shenzhen',
            'Rio de Janeiro',
            'Kinshasa',
            'Tianjin',
            'Paris',
            'Lima'
        ]
    }, {
        'id': 1,
        'is_name_things': True,
        'total_answers': 54,
        'prompt': "Name at least 32 African countries",
        'passing_score': 32,
        'answers': {
            "algeria": 0,
            "angola": 1,
            "benin": 2,
            "botswana": 3,
            "burkina faso": 4,
            "burundi": 5,
            "cabo verde": 6,
            "cameroon": 7,
            "central african republic": 8,
            "chad": 9,
            "comoros": 10,
            "congo democratic republic of the": 12,
            "democratic republic of the congo": 12,
            "congo republic of the": 11,
            "republic of the congo": 11,
            "cote d'ivoire": 13,
            "cote d ivoire": 13,
            "cote divoire": 13,
            "cote ivoire": 13,
            "djibouti": 14,
            "egypt": 15,
            "equatorial guinea": 16,
            "eritrea": 17,
            "ethiopia": 18,
            "gabon": 19,
            "gambia": 20,
            "ghana": 21,
            "guinea": 22,
            "guinea bissau": 23,
            "kenya": 24,
            "lesotho": 25,
            "liberia": 26,
            "libya": 27,
            "madagascar": 28,
            "malawi": 29,
            "mali": 30,
            "mauritania": 31,
            "mauritius": 32,
            "morocco": 33,
            "mozambique": 34,
            "namibia": 35,
            "niger": 36,
            "nigeria": 37,
            "rwanda": 38,
            "sao tome and principe": 39,
            "senegal": 40,
            "seychelles": 41,
            "sierra leone": 42,
            "somalia": 43,
            "south africa": 44,
            "south sudan": 45,
            "sudan": 46,
            "swaziland": 47,
            "tanzania": 48,
            "togo": 49,
            "tunisia": 50,
            "uganda": 51,
            "zambia": 52,
            "zimbabwe": 53
        },
        'names': [
            "Algeria",
            "Angola",
            "Benin",
            "Botswana",
            "Burkina Faso",
            "Burundi",
            "Cabo Verde",
            "Cameroon",
            "Central African Republic",
            "Chad",
            "Comoros",
            "Congo Republic of the",
            "Congo Democratic Republic of the",
            "Cote d'Ivoire",
            "Djibouti",
            "Egypt",
            "Equatorial Guinea",
            "Eritrea",
            "Ethiopia",
            "Gabon",
            "Gambia",
            "Ghana",
            "Guinea",
            "Guinea Bissau",
            "Kenya",
            "Lesotho",
            "Liberia",
            "Libya",
            "Madagascar",
            "Malawi",
            "Mali",
            "Mauritania",
            "Mauritius",
            "Morocco",
            "Mozambique",
            "Namibia",
            "Niger",
            "Nigeria",
            "Rwanda",
            "Sao Tome and Principe",
            "Senegal",
            "Seychelles",
            "Sierra Leone",
            "Somalia",
            "South Africa",
            "South Sudan",
            "Sudan",
            "Swaziland",
            "Tanzania",
            "Togo",
            "Tunisia",
            "Uganda",
            "Zambia",
            "Zimbabwe"
        ]
    }
]
