# -*- coding: utf-8; -*-

QUESTIONS = [
    {
        'id': 2,
        'is_name_things': True,
        'total_answers': 34,
        'prompt': "Name any 14 Oscar Best Pictures since 1980",
        'passing_score': 9,
        'answers': {'the lord of the rings': 10, 'dance with wolves': 23, 'ordinary people': 33, "the king's speech": 4, 'the lord of the rings: the return of the king': 10, 'gladiator': 13, 'the hurt locker': 5, 'forest gump': 19, '12 years a slave': 1, 'the artist': 3, 'platoon': 27, 'chicago': 11, 'a beautiful mind': 12, 'million dollar baby': 9, 'driving miss daisy': 24, 'crash': 8, 'american beauty': 14, "schindler's list": 20, 'slumdog millionaire': 6, 'rain man': 25, 'unforgiven': 21, 'amadeus': 29, 'argo': 2, 'braveheart': 18, 'out of africa': 28, 'chariots of fire': 32, 'the last emperor': 26, 'titanic': 16, 'no country for old men': 7, 'birdman': 0, 'the english patient': 17, 'gandhi': 31, 'shakespeare in love': 15, 'the silence of the lambs': 22, 'terms of endearment': 30},
        'names': [
            'Birdman',
            '12 Years a Slave',
            'Argo',
            'The Artist',
            "The King's Speech",
            'The Hurt Locker',
            'Slumdog Millionaire',
            'No Country for Old Men',
            'Crash',
            'Million Dollar Baby',
            'The Lord of the Rings: The Return of the King',
            'Chicago',
            'A Beautiful Mind',
            'Gladiator',
            'American Beauty',
            'Shakespeare in Love',
            'Titanic',
            'The English Patient',
            'Braveheart',
            'Forest Gump',
            "Schindler's List",
            'Unforgiven',
            'The Silence of the Lambs',
            'Dance with Wolves',
            'Driving Miss Daisy',
            'Rain Man',
            'The Last Emperor',
            'Platoon',
            'Out of Africa',
            'Amadeus',
            'Terms of Endearment',
            'Gandhi',
            'Chariots of Fire',
            'Ordinary People'
        ]
    }, {
        'id': 0,
        'is_name_things': True,
        'total_answers': 30,
        'prompt': "Name 7 of the Largest 30 Cities in the World",
        'passing_score': 7,
        'answers': {
            "tokyo": 0,
            "jakarta": 1,
            "karachi": 2,
            "manila": 3,
            "delhi": 4,
            "seoul": 5,
            "shanghai": 6,
            "beijing": 7,
            "new york city": 8,
            "new york": 8,
            "guangzhou": 9,
            "sao paulo": 10,
            "mexico city": 11,
            "mumbai": 12,
            "osaka": 13,
            "lagos": 14,
            "moscow": 15,
            "dhaka": 16,
            "lahore": 17,
            "los angeles": 18,
            "bangkok": 19,
            "kolkata": 20,
            "buenos aires": 21,
            "tehran": 22,
            "istanbul": 23,
            "shenzhen": 24,
            "rio de janeiro": 25,
            "kinshasa": 26,
            "tianjin": 27,
            "paris": 28,
            "lima": 29
        },
        'names': [
            'Tokyo',
            'Jakarta',
            'Karachi',
            'Manila',
            'Delhi',
            'Seoul',
            'Shanghai',
            'Beijing',
            'New York City',
            'Guangzhou',
            'Sao Paulo',
            'Mexico City',
            'Mumbai',
            'Osaka',
            'Lagos',
            'Moscow',
            'Dhaka',
            'Lahore',
            'Los Angeles',
            'Bangkok',
            'Kolkata',
            'Buenos Aires',
            'Tehran',
            'Istanbul',
            'Shenzhen',
            'Rio de Janeiro',
            'Kinshasa',
            'Tianjin',
            'Paris',
            'Lima'
        ]
    }, {
        'id': 1,
        'is_name_things': True,
        'total_answers': 54,
        'prompt': "Name at least 9 African countries",
        'passing_score': 9,
        'answers': {
            "algeria": 0,
            "angola": 1,
            "benin": 2,
            "botswana": 3,
            "burkina faso": 4,
            "burundi": 5,
            "cabo verde": 6,
            "cameroon": 7,
            "central african republic": 8,
            "chad": 9,
            "comoros": 10,
            "congo democratic republic of the": 12,
            "democratic republic of the congo": 12,
            "congo republic of the": 11,
            "republic of the congo": 11,
            "cote d'ivoire": 13,
            "cote d ivoire": 13,
            "cote divoire": 13,
            "cote ivoire": 13,
            "djibouti": 14,
            "egypt": 15,
            "equatorial guinea": 16,
            "eritrea": 17,
            "ethiopia": 18,
            "gabon": 19,
            "gambia": 20,
            "ghana": 21,
            "guinea": 22,
            "guinea bissau": 23,
            "kenya": 24,
            "lesotho": 25,
            "liberia": 26,
            "libya": 27,
            "madagascar": 28,
            "malawi": 29,
            "mali": 30,
            "mauritania": 31,
            "mauritius": 32,
            "morocco": 33,
            "mozambique": 34,
            "namibia": 35,
            "niger": 36,
            "nigeria": 37,
            "rwanda": 38,
            "sao tome and principe": 39,
            "senegal": 40,
            "seychelles": 41,
            "sierra leone": 42,
            "somalia": 43,
            "south africa": 44,
            "south sudan": 45,
            "sudan": 46,
            "swaziland": 47,
            "tanzania": 48,
            "togo": 49,
            "tunisia": 50,
            "uganda": 51,
            "zambia": 52,
            "zimbabwe": 53
        },
        'names': [
            "Algeria",
            "Angola",
            "Benin",
            "Botswana",
            "Burkina Faso",
            "Burundi",
            "Cabo Verde",
            "Cameroon",
            "Central African Republic",
            "Chad",
            "Comoros",
            "Congo Republic of the",
            "Congo Democratic Republic of the",
            "Cote d'Ivoire",
            "Djibouti",
            "Egypt",
            "Equatorial Guinea",
            "Eritrea",
            "Ethiopia",
            "Gabon",
            "Gambia",
            "Ghana",
            "Guinea",
            "Guinea Bissau",
            "Kenya",
            "Lesotho",
            "Liberia",
            "Libya",
            "Madagascar",
            "Malawi",
            "Mali",
            "Mauritania",
            "Mauritius",
            "Morocco",
            "Mozambique",
            "Namibia",
            "Niger",
            "Nigeria",
            "Rwanda",
            "Sao Tome and Principe",
            "Senegal",
            "Seychelles",
            "Sierra Leone",
            "Somalia",
            "South Africa",
            "South Sudan",
            "Sudan",
            "Swaziland",
            "Tanzania",
            "Togo",
            "Tunisia",
            "Uganda",
            "Zambia",
            "Zimbabwe"
        ]
    }, {
        'id': 3,
        'is_name_things': True,
        'total_answers': 34,
        'prompt': "Name any 7 states of India",
        'passing_score': 7,
        'answers': {'jammu': 9, 'kashmir': 9, 'orissa': 19, 'telangana': 24, 'uttarakhand': 27, 'karnataka': 11, 'himachal pradesh': 8, 'mizoram': 17, 'tamil nadu': 23, 'haryana': 7, 'punjab': 20, 'goa': 5, 'chhattisgarh': 4, 'kerala': 12, 'bihar': 3, 'west bengal': 28, 'andhra pradesh': 0, 'jharkhand': 10, 'meghalaya': 16, 'assam': 2, 'manipur': 15, 'rajasthan': 21, 'arunachal pradesh': 1, 'sikkim': 22, 'maharashtra': 14, 'maharastra': 14, 'jammu & kashmir': 9, 'nagaland': 18, 'madhya pradesh': 13, 'uttar pradesh': 26, 'gujarat': 6, 'odisha': 19, 'tripura': 25},
        'names': [
            'Andhra Pradesh',
            'Arunachal Pradesh',
            'Assam',
            'Bihar',
            "Chhattisgarh",
            'Goa',
            'Gujarat',
            'Haryana',
            'Himachal Pradesh',
            'Jammu & Kashmir',
            'Jharkhand',
            'Karnataka',
            'Kerala',
            'Madhya Pradesh',
            'Maharashtra',
            'Manipur',
            'Meghalaya',
            'Mizoram',
            'Nagaland',
            'Odisha (Orissa)',
            "Punjab",
            'Rajasthan',
            'Sikkim',
            'Tamil Nadu',
            'Telangana',
            'Tripura',
            'Uttar Pradesh',
            'Uttarakhand',
            'West Bengal'
        ]
    }, {
        'id': 4,
        'is_name_things': True,
        'total_answers': 41,
        'prompt': "Name any 8 presidents of the United States of America",
        'passing_score': 8,
        'answers': {'george w bush': 42, 'james buchanan': 14, 'andrew johnson': 16, 'william harrison': 8, 'clinton': 41, 'abraham lincoln': 15, 'lyndon johnson': 35, 'kennedy': 34, 'ulysses grant': 17, 'william mckinley': 24, 'john kennedy': 34, 'william h. taft': 26, 'harrison': 8, 'harry truman': 32, 'george washington': 0, 'dwight eisenhower': 33, 'william h. harrison': 8, 'ulysses s. grant': 17, 'martin van buren': 7, 'richard nixon': 36, 'herbert hoover': 30, 'warren harding': 28, 'woodrow wilson': 27, 'john tyler': 9, 'thomas jefferson': 2, 'ronald reagan': 39, 'bill clinton': 41, 'jefferson': 2, 'warren g. harding': 28, 'polk': 10, 'eisenhower': 33, 'james garfield': 19, 'franklin roosevelt': 31, 'grover cleveland': 23, 'chester arthur': 20, 'lyndon b. johnson': 35, 'millard fillmore': 12, 'truman': 32, 'harry s. truman': 32, 'calvin coolidge': 29, 'james monroe': 4, 'george h. w. bush': 40, 'john quincy adams': 5, 'zachary taylor': 11, 'chester a. arthur': 20, 'george w. bush': 41, 'franklin d. roosevelt': 31, 'barack obama': 21, 'theodore roosevelt': 25, 'rutherford b. hayes': 18, 'william taft': 26, 'james polk': 10, 'james madison': 3, 'jimmy carter': 38, 'obama': 21, 'lincoln': 15, 'john adams': 1, 'benjamin harrison': 22, 'franklin pierce': 13, 'john f. kennedy': 34, 'rutherford hayes': 18, 'gerald ford': 37, 'dwight d. eisenhower': 33, 'james k. polk': 10, 'andrew jackson': 6},
        'names': ['George Washington', 'John Adams', 'Thomas Jefferson', 'James Madison', 'James Monroe', 'John Quincy Adams', 'Andrew Jackson', 'Martin Van Buren', 'William H. Harrison', 'John Tyler', 'James K. Polk', 'Zachary Taylor', 'Millard Fillmore', 'Franklin Pierce', 'James Buchanan', 'Abraham Lincoln', 'Andrew Johnson', 'Ulysses S. Grant', 'Rutherford B. Hayes', 'James Garfield', 'Chester A. Arthur', 'Barack Obama', 'Benjamin Harrison', 'Grover Cleveland', 'William McKinley', 'Theodore Roosevelt', 'William H. Taft', 'Woodrow Wilson', 'Warren G. Harding', 'Calvin Coolidge', 'Herbert Hoover', 'Franklin D. Roosevelt', 'Harry S. Truman', 'Dwight D. Eisenhower', 'John F. Kennedy', 'Lyndon B. Johnson', 'Richard Nixon', 'Gerald Ford', 'Jimmy Carter', 'Ronald Reagan', 'George H. W. Bush', 'Bill Clinton', 'George W. Bush']
    }
]
